version: '3.8'

services:
  app:
    build: .
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:

      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=wallet
      - DB_USER=postgres
      - DB_PASSWORD=postgres

      - DB_POOL_SIZE=50
      - DB_MIN_IDLE=10
      - DB_TIMEOUT=10000

      - SERVER_MAX_THREADS=200
      - SERVER_MIN_THREADS=20
      - SERVER_MAX_CONNECTIONS=8192
      - SERVER_ACCEPT_COUNT=100
      - SERVER_CONNECTION_TIMEOUT=20000

      - HIBERNATE_STATISTICS=false
    depends_on:
      - db
    networks:
      - wallet-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  db:
    image: postgres:14
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

      - POSTGRES_MAX_CONNECTIONS=200
      - POSTGRES_SHARED_BUFFERS=256MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=1GB
      - POSTGRES_MAINTENANCE_WORK_MEM=256MB
      - POSTGRES_CHECKPOINT_COMPLETION_TARGET=0.9
      - POSTGRES_WAL_BUFFERS=16MB
      - POSTGRES_DEFAULT_STATISTICS_TARGET=100
      - POSTGRES_RANDOM_PAGE_COST=1.1
      - POSTGRES_EFFECTIVE_IO_CONCURRENCY=200
      - POSTGRES_WORK_MEM=16MB
      - POSTGRES_MIN_WAL_SIZE=1GB
      - POSTGRES_MAX_WAL_SIZE=4GB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - wallet-network
    command: >
      postgres
      -c max_connections=${POSTGRES_MAX_CONNECTIONS:-200}
      -c shared_buffers=${POSTGRES_SHARED_BUFFERS:-256MB}
      -c effective_cache_size=${POSTGRES_EFFECTIVE_CACHE_SIZE:-1GB}
      -c maintenance_work_mem=${POSTGRES_MAINTENANCE_WORK_MEM:-256MB}
      -c checkpoint_completion_target=${POSTGRES_CHECKPOINT_COMPLETION_TARGET:-0.9}
      -c wal_buffers=${POSTGRES_WAL_BUFFERS:-16MB}
      -c default_statistics_target=${POSTGRES_DEFAULT_STATISTICS_TARGET:-100}
      -c random_page_cost=${POSTGRES_RANDOM_PAGE_COST:-1.1}
      -c effective_io_concurrency=${POSTGRES_EFFECTIVE_IO_CONCURRENCY:-200}
      -c work_mem=${POSTGRES_WORK_MEM:-16MB}
      -c min_wal_size=${POSTGRES_MIN_WAL_SIZE:-1GB}
      -c max_wal_size=${POSTGRES_MAX_WAL_SIZE:-4GB}
      -c log_min_duration_statement=200
      -c idle_in_transaction_session_timeout=10000
      -c lock_timeout=1000
      -c statement_timeout=60000
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G

networks:
  wallet-network:
    driver: bridge

volumes:
  postgres-data: 